eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8767
spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
  rabbitmq:
    host: localhost
    port: 5672
    username:
    password:
