eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/collinsuns/SpringCloudDemo/
          searchPaths: data2demo
          username: your_username
          password: your_password
      label: master
